Repository quantified-uncertainty/squiggle, pull requests merged in 2022-03, with the labels that each got.

#72 Components in docs
  .github/workflows/ci.yaml
  packages/components/src/spec-distributions.json
  packages/squiggle-lang/README.md
  packages/website/babel.config.js
  packages/website/docs/Functions.mdx
  packages/website/docs/Future-Features.md
  packages/website/docs/Introduction.md
  packages/website/docs/Javscript-library.md
  packages/website/docs/Language.md
  packages/website/docs/Language.mdx
  packages/website/docs/Three-Types-Of-Distributions.md
  packages/website/docusaurus.config.js
  packages/website/src/components/SquiggleEditor.jsx
Labels: documentation

#68 Reducer dev
  .gitignore
  packages/squiggle-lang/__tests__/Reducer/Reducer_Dispatch/Reducer_Dispatch_BuiltIn_test.res
  packages/squiggle-lang/__tests__/Reducer/Reducer_Extension/ReducerExtension_CodeTreeValue_test.res
  packages/squiggle-lang/__tests__/Reducer/Reducer_MathJs/Reducer_MathJsEval_test.res
  packages/squiggle-lang/__tests__/Reducer/Reducer_MathJs/Reducer_MathJsParse_test.res
  packages/squiggle-lang/__tests__/Reducer/Reducer_TestHelpers.res
  packages/squiggle-lang/__tests__/Reducer/Reducer_test.res
  packages/squiggle-lang/bsconfig.json
  packages/squiggle-lang/package.json
  packages/squiggle-lang/src/rescript/Reducer/README.md
  packages/squiggle-lang/src/rescript/Reducer/Reducer.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_CodeTree/Reducer_CodeTree.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_CodeTree/Reducer_CodeTree_T.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Dispatch/Reducer_Dispatch.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Dispatch/Reducer_Dispatch_BuiltIn.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Error.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Extension/Reducer_Extension.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Extension/Reducer_Extension_CodeTreeValue.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Extension/Reducer_Extension_ReducerLibrary.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Extra/Reducer_Extra.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Extra/Reducer_Extra_Array.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Extra/Reducer_Extra_List.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Js/Reducer_Js.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Js/Reducer_Js_Gate.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_MathJs/Reducer_MathJs.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_MathJs/Reducer_MathJs_Eval.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_MathJs/Reducer_MathJs_Parse.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_MathJs/Reducer_MathJs_ToCodeTree.res
  yarn.lock
Labels: programming language

#101 Hotfix `README.md`s, with a couple piggybacked changes
  .github/ISSUE_TEMPLATE/developer-bug.md
  .github/ISSUE_TEMPLATE/pl.md
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  README.md
  packages/squiggle-lang/README.md
  packages/website/README.md
Labels: documentation

#136 Remove mdx dependency
  packages/website/package.json
  yarn.lock
Labels: dependencies

#69 Generic Distribution Library: First Pass
  packages/squiggle-lang/__tests__/GenericDist/GenericOperation__Test.res
  packages/squiggle-lang/src/rescript/GenericDist/GenericDist.res
  packages/squiggle-lang/src/rescript/GenericDist/GenericDist.resi
  packages/squiggle-lang/src/rescript/GenericDist/GenericDist_GenericOperation.res
  packages/squiggle-lang/src/rescript/GenericDist/GenericDist_GenericOperation.resi
  packages/squiggle-lang/src/rescript/GenericDist/GenericDist_Types.res
  packages/squiggle-lang/src/rescript/GenericDist/README.md
  packages/squiggle-lang/src/rescript/pointSetDist/AlgebraicShapeCombination.res
  packages/squiggle-lang/src/rescript/pointSetDist/PointSetDist.res
  packages/squiggle-lang/src/rescript/pointSetDist/XYShape.res
  packages/squiggle-lang/src/rescript/sampleSet/SampleSet.res
  packages/squiggle-lang/src/rescript/symbolicDist/SymbolicDist.res
  packages/squiggle-lang/src/rescript/utility/E.res
  packages/squiggle-lang/src/rescript/utility/Operation.res
Labels: programming language
