Repository quantified-uncertainty/squiggle, pull requests merged in 2022-07, with the labels that each got.

#803 Reducer modules - define function returning result
  packages/squiggle-lang/__tests__/Reducer/Reducer_Module/Reducer_Module_test.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Expression/Reducer_Expression_T.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Module/Reducer_Module.res
Labels: programming language

#796 Collapsible records in playground output
  packages/components/README.md
  packages/components/package.json
  packages/components/src/components/DistributionChart.tsx
  packages/components/src/components/SquiggleChart.tsx
  packages/components/src/components/SquiggleContainer.tsx
  packages/components/src/components/SquigglePlayground.tsx
  packages/components/src/components/SquiggleViewer/ExpressionViewer.tsx
  packages/components/src/components/SquiggleViewer/ItemSettingsMenu.tsx
  packages/components/src/components/SquiggleViewer/VariableBox.tsx
  packages/components/src/components/SquiggleViewer/ViewerContext.ts
  packages/components/src/components/SquiggleViewer/index.tsx
  packages/components/src/components/SquiggleViewer/utils.ts
  packages/components/src/components/ViewSettings.tsx
  packages/components/src/components/ui/Checkbox.tsx
  packages/components/src/components/ui/HeadedSection.tsx
  packages/components/src/components/ui/InputItem.tsx
  packages/components/src/components/ui/Modal.tsx
  packages/components/src/components/ui/Text.tsx
  packages/components/src/components/ui/Tooltip.tsx
  packages/components/src/lib/distributionSpecBuilder.ts
  packages/components/src/lib/distributionUtils.ts
  packages/vscode-ext/media/previewWebview.js
  packages/vscode-ext/package.json
  packages/website/docusaurus.config.js
  packages/website/src/pages/playground.js
  yarn.lock
Labels: Components / Visualization

#905 fixes #904. E.O.default performance
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Continuous.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Discrete.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/MixedShapeBuilder.res
  packages/squiggle-lang/src/rescript/ReducerInterface/ReducerInterface_ExternalLibrary.res
  packages/squiggle-lang/src/rescript/Utility/E.res
Labels: bug (numeric), bug (interpreter/parser)
