Repository quantified-uncertainty/squiggle, pull requests merged in 2022-04, with the labels that each got.

#181 Rescript Organization Refactor #1
  packages/squiggle-lang/__tests__/DistTypes__Test.res
  packages/squiggle-lang/__tests__/GenericDist/GenericOperation__Test.res
  packages/squiggle-lang/src/js/index.ts
  packages/squiggle-lang/src/rescript/Distributions/DistributionOperation/DistributionOperation.res
  packages/squiggle-lang/src/rescript/Distributions/DistributionOperation/DistributionOperation.resi
  packages/squiggle-lang/src/rescript/Distributions/DistributionTypes.res
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/GenericDist.res
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/GenericDist.resi
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/GenericDist_Types.res
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/README.md
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/AlgebraicShapeCombination.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Continuous.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Discrete.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Distributions.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Mixed.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/MixedShapeBuilder.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/PointSetDist.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/PointSetTypes.res
  packages/squiggle-lang/src/rescript/Distributions/SampleSetDist/Bandwidth.res
  packages/squiggle-lang/src/rescript/Distributions/SampleSetDist/KdeLibrary.js
  packages/squiggle-lang/src/rescript/Distributions/SampleSetDist/SampleSet.res
  packages/squiggle-lang/src/rescript/Distributions/SymbolicDist/SymbolicDist.res
  packages/squiggle-lang/src/rescript/Distributions/SymbolicDist/SymbolicDistTypes.res
  packages/squiggle-lang/src/rescript/OldInterpreter/AST.res
  packages/squiggle-lang/src/rescript/OldInterpreter/ASTEvaluator.res
  packages/squiggle-lang/src/rescript/OldInterpreter/ASTTypes.res
  packages/squiggle-lang/src/rescript/OldInterpreter/DistPlus.res
  packages/squiggle-lang/src/rescript/OldInterpreter/typeSystem/HardcodedFunctions.res
  packages/squiggle-lang/src/rescript/OldInterpreter/typeSystem/TypeSystem.res
  packages/squiggle-lang/src/rescript/OldParser/Parser.res
  packages/squiggle-lang/src/rescript/ReducerInterface/ReducerInterface_GenericDistribution.res
  packages/squiggle-lang/src/rescript/Utility/E.res
  packages/squiggle-lang/src/rescript/Utility/Hash.res
  packages/squiggle-lang/src/rescript/Utility/Jstat.res
  packages/squiggle-lang/src/rescript/Utility/Lodash.res
  packages/squiggle-lang/src/rescript/Utility/Mathjs.res
  packages/squiggle-lang/src/rescript/Utility/MathjsWrapper.js
  packages/squiggle-lang/src/rescript/Utility/Operation.res
  packages/squiggle-lang/src/rescript/Utility/SamplingInputs.res
  packages/squiggle-lang/src/rescript/Utility/Sparklines.res
  packages/squiggle-lang/src/rescript/Utility/XYShape.res
  packages/squiggle-lang/src/rescript/pointSetDist/PointSetTypes.res
Labels: Lang: GenericOperation

#148 Move Playground to components
  .gitignore
  package.json
  packages/components/.storybook/main.js
  packages/components/.storybook/preview.js
  packages/components/README.md
  packages/components/package.json
  packages/components/src/CodeEditor.tsx
  packages/components/src/SquiggleChart.tsx
  packages/components/src/SquiggleEditor.tsx
  packages/components/src/SquigglePlayground.tsx
  packages/components/src/index.ts
  packages/components/src/spec-distributions.json
  packages/components/src/stories/SquiggleEditor.stories.mdx
  packages/components/src/stories/SquigglePlayground.stories.mdx
  packages/components/tsconfig.json
  packages/components/webpack.config.js
  packages/playground/.gitignore
  packages/playground/README.md
  packages/playground/netlify.toml
  packages/playground/package.json
  packages/playground/postcss.config.js
  packages/playground/src/Index.tsx
  packages/playground/src/components/CodeEditor.tsx
  packages/playground/src/components/DistBuilder.tsx
  packages/playground/src/index.html
  packages/playground/src/styles/antd.css
  packages/playground/src/styles/index.css
  packages/playground/tailwind.config.js
  packages/playground/tsconfig.json
  packages/playground/yarn.nix
  packages/squiggle-lang/package.json
  yarn.lock
Labels: Components / Visualization

#229 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ops & testing

#232 Testing discipline: algebraic operations
  packages/squiggle-lang/__tests__/Distributions/DistributionOperation_test.res
  packages/squiggle-lang/__tests__/Distributions/GenericDist_Fixtures.res
  packages/squiggle-lang/__tests__/Distributions/Invariants/AlgebraicCombination_test.res
  packages/squiggle-lang/__tests__/Distributions/Invariants/Means_test.res
  packages/squiggle-lang/__tests__/Distributions/Mixture_test.res
  packages/squiggle-lang/__tests__/Distributions/Symbolic_test.res
  packages/squiggle-lang/__tests__/TestHelpers.res
  packages/squiggle-lang/__tests__/Utility_test.res
  packages/squiggle-lang/package.json
  packages/squiggle-lang/src/rescript/Distributions/DistributionOperation/DistributionOperation.res
  packages/squiggle-lang/src/rescript/Distributions/DistributionTypes.res
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/GenericDist.res
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/GenericDist_Types.res
  packages/squiggle-lang/src/rescript/Distributions/SymbolicDist/SymbolicDist.res
  packages/squiggle-lang/src/rescript/TypescriptInterface.res
  packages/squiggle-lang/src/rescript/Utility/E.res
Labels: ops & testing

#246 build rescript for codeql
  .github/workflows/codeql-analysis.yml
Labels: ops & testing

#251 migrated `invariants.md` to `docusaurus`
  packages/website/README.md
  packages/website/docs/Features/Javascript-Libraries.md
  packages/website/docs/Internal/Invariants.md
  packages/website/docusaurus.config.js
  packages/website/package.json
  packages/website/sidebars.js
  yarn.lock
Labels: documentation, testing (squiggle-lang)

#257 Improvements to `Means_test.res` (and `expectErrorToBeBounded`)
  packages/squiggle-lang/__tests__/Distributions/Invariants/Means_test.res
  packages/squiggle-lang/__tests__/TestHelpers.res
  packages/squiggle-lang/src/rescript/ReducerInterface/ReducerInterface_GenericDistribution.res
  packages/squiggle-lang/src/rescript/Utility/E.res
Labels: testing (squiggle-lang)

#278 feat: Audit SymbolicDist.res
  packages/squiggle-lang/__tests__/ReducerInterface/ReducerInterface_Distribution_test.res
  packages/squiggle-lang/src/rescript/Distributions/SymbolicDist/SymbolicDist.res
  packages/website/docs/Internal/ProcessingConfidenceIntervals.md
Labels: programming language, bug (numerics)

#286 issue templates patch
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/future.md
  .github/ISSUE_TEMPLATE/ops-testing.md
Labels: operations

#288 declarative netlify
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/ops-testing.md
  README.md
  flake-compat.nix
  flake.lock
  flake.nix
  packages/components/netlify.toml
  packages/website/netlify.toml
Labels: operations

#289 fix: std of lognormal symbolic division
  packages/squiggle-lang/__tests__/ReducerInterface/ReducerInterface_Distribution_test.res
  packages/squiggle-lang/src/rescript/Distributions/SymbolicDist/SymbolicDist.res
Labels: bug (numeric)

#258 Playground improvements with new types
  .github/ISSUE_TEMPLATE/user-bug.md
  packages/components/package.json
  packages/components/src/components/CodeEditor.tsx
  packages/components/src/components/DistributionChart.tsx
  packages/components/src/components/SquiggleChart.tsx
  packages/components/src/components/SquiggleEditor.tsx
  packages/components/src/components/SquigglePlayground.tsx
  packages/components/src/stories/SquiggleChart.stories.mdx
  packages/components/src/stories/SquigglePlayground.stories.mdx
  packages/squiggle-lang/src/js/index.ts
  packages/website/src/pages/playground.js
  yarn.lock
Labels: Components / Visualization

#322 Documentation apr18
  .github/workflows/codeql-analysis.yml
  .parcelrc
  packages/website/.prettierignore
  packages/website/docs/Features/Functions.mdx
  packages/website/docs/Internal/Invariants.md
  packages/website/docusaurus.config.js
  packages/website/src/pages/index.js
  packages/website/static/img/favicon.ico
  packages/website/static/img/quri-logo.png
Labels: documentation

#316 `fast-check` in typescript
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  nixos.sh
  packages/squiggle-lang/.gitignore
  packages/squiggle-lang/__tests__/TS/JS_test.ts
  packages/squiggle-lang/__tests__/TS/Jstat_test.ts
  packages/squiggle-lang/__tests__/TS/Parser_test.ts
  packages/squiggle-lang/__tests__/TS/PointSet_test.ts
  packages/squiggle-lang/__tests__/TS/SampleSet_test.ts
  packages/squiggle-lang/__tests__/TS/Scalars_test.ts
  packages/squiggle-lang/__tests__/TS/Symbolic_test.ts
  packages/squiggle-lang/__tests__/TS/TestHelpers.ts
  packages/squiggle-lang/jest.config.js
  packages/squiggle-lang/lint.sh
  packages/squiggle-lang/package.json
  yarn.lock
Labels: ops & testing, testing (squiggle-lang)

#332 Fix warnings
  packages/components/src/components/SquiggleChart.tsx
  packages/components/src/components/SquiggleEditor.tsx
  packages/squiggle-lang/bsconfig.json
  packages/squiggle-lang/package.json
  packages/squiggle-lang/src/js/index.ts
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/GenericDist.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Continuous.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Discrete.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Mixed.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/PointSetDist.res
  packages/squiggle-lang/src/rescript/OldInterpreter/AST.res
  packages/squiggle-lang/src/rescript/OldInterpreter/ASTEvaluator.res
  packages/squiggle-lang/src/rescript/OldInterpreter/ASTTypes.res
  packages/squiggle-lang/src/rescript/OldInterpreter/DistPlus.res
  packages/squiggle-lang/src/rescript/OldInterpreter/typeSystem/HardcodedFunctions.res
  packages/squiggle-lang/src/rescript/OldInterpreter/typeSystem/TypeSystem.res
  packages/squiggle-lang/src/rescript/OldParser/Parser.res
  packages/squiggle-lang/src/rescript/ProgramEvaluator.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Expression/Reducer_Expression.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_MathJs/Reducer_MathJs_Eval.res
  packages/squiggle-lang/src/rescript/ReducerInterface/ReducerInterface_GenericDistribution.res
  packages/squiggle-lang/src/rescript/Utility/E.res
  packages/squiggle-lang/src/rescript/Utility/Sparklines.res
  packages/squiggle-lang/src/rescript/Utility/XYShape.res
  yarn.lock
Labels: programming language

#338 grammar document
  packages/website/docs/Internal/Grammar.md
Labels: documentation, programming language, Lang: Parser

#333 Bindings in and Out
  packages/squiggle-lang/__tests__/Reducer/Reducer_TestHelpers.res
  packages/squiggle-lang/__tests__/Reducer/Reducer_externalBindings_test.res
  packages/squiggle-lang/__tests__/Reducer/Reducer_ternaryOperator_test.res
  packages/squiggle-lang/__tests__/Reducer/Reducer_test.res
  packages/squiggle-lang/package.json
  packages/squiggle-lang/src/rescript/Reducer/Reducer.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer.resi
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Dispatch/Reducer_Dispatch.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Dispatch/Reducer_Dispatch_BuiltInMacros.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_Expression/Reducer_Expression.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_MathJs/Reducer_MathJs_ToExpression.res
  packages/squiggle-lang/src/rescript/ReducerInterface/ReducerInterface_ExpressionValue.res
  packages/squiggle-lang/src/rescript/ReducerInterface/ReducerInterface_ExternalLibrary.res
  yarn.lock
Labels: programming language

#345 Change NaN operations to results
  packages/squiggle-lang/__tests__/Distributions/DistributionOperation_test.res
  packages/squiggle-lang/__tests__/Distributions/GenericDist_Fixtures.res
  packages/squiggle-lang/__tests__/Distributions/Invariants/AlgebraicCombination_test.res
  packages/squiggle-lang/__tests__/Distributions/Invariants/Means_test.res
  packages/squiggle-lang/__tests__/ReducerInterface/ReducerInterface_Distribution_test.res
  packages/squiggle-lang/__tests__/TS/Symbolic_test.ts
  packages/squiggle-lang/jest.config.js
  packages/squiggle-lang/src/rescript/Distributions/DistributionOperation/DistributionOperation.res
  packages/squiggle-lang/src/rescript/Distributions/DistributionOperation/DistributionOperation.resi
  packages/squiggle-lang/src/rescript/Distributions/DistributionTypes.res
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/GenericDist.res
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/GenericDist.resi
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/GenericDist_Types.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/AlgebraicShapeCombination.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Continuous.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Discrete.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Distributions.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/Mixed.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/PointSetDist.res
  packages/squiggle-lang/src/rescript/Distributions/PointSetDist/PointSetTypes.res
  packages/squiggle-lang/src/rescript/Distributions/SampleSetDist/SampleSetDist.res
  packages/squiggle-lang/src/rescript/Distributions/SampleSetDist/SampleSetDist_ToPointSet.res
  packages/squiggle-lang/src/rescript/Distributions/SymbolicDist/SymbolicDist.res
  packages/squiggle-lang/src/rescript/Distributions/SymbolicDist/SymbolicDistTypes.res
  packages/squiggle-lang/src/rescript/Reducer/Reducer_ErrorValue.res
  packages/squiggle-lang/src/rescript/ReducerInterface/ReducerInterface_ExpressionValue.res
  packages/squiggle-lang/src/rescript/ReducerInterface/ReducerInterface_GenericDistribution.res
  packages/squiggle-lang/src/rescript/TypescriptInterface.res
  packages/squiggle-lang/src/rescript/Utility/E.res
  packages/squiggle-lang/src/rescript/Utility/Operation.res
  packages/squiggle-lang/src/rescript/Utility/XYShape.res
  packages/website/docs/Features/Functions.mdx
Labels: programming language

#375 Fixing error in 371
  packages/components/package.json
  packages/squiggle-lang/package.json
  packages/website/package.json
  yarn.lock
Labels: ops & testing, dependencies

#401 minor docs update
  .prettierignore
  packages/website/docs/Features/Functions.mdx
  packages/website/docs/Internal/Grammar.md
Labels: documentation

#402 Algebraic combination refactor
  packages/squiggle-lang/__tests__/ReducerInterface/ReducerInterface_Distribution_test.res
  packages/squiggle-lang/src/rescript/Distributions/GenericDist/GenericDist.res
  packages/squiggle-lang/src/rescript/Utility/Operation.res
Labels: programming language

#406 `Language.mdx` changes and `examples`; misc docs improvements
  examples/decay.squiggle
  examples/givedirectly.squiggle
  examples/wholenumberassignmentevaluation.squiggle
  packages/website/docs/Discussions/Gallery.md
  packages/website/docs/Discussions/Three-Formats-Of-Distributions.md
  packages/website/docs/Features/Language.mdx
  packages/website/docs/Features/Node-Packages.md
  packages/website/docs/Internal/Processing-Confidence-Intervals.md
  packages/website/docs/Introduction.md
  packages/website/static/img/docusaurus.png
  packages/website/static/img/favicon.ico
  packages/website/static/img/logo.svg
  packages/website/static/img/quri-logo-with-QURI-written-underneath.png
  packages/website/static/img/quri-logo.png
  packages/website/static/img/undraw_docusaurus_mountain.svg
  packages/website/static/img/undraw_docusaurus_react.svg
  packages/website/static/img/undraw_docusaurus_tree.svg
Labels: documentation

#440 `fromSamples`
  packages/squiggle-lang/__tests__/TS/SampleSet_test.ts
  packages/squiggle-lang/src/rescript/Distributions/DistributionOperation/DistributionOperation.res
  packages/squiggle-lang/src/rescript/Distributions/DistributionOperation/DistributionOperation.resi
  packages/squiggle-lang/src/rescript/Distributions/DistributionTypes.res
  packages/squiggle-lang/src/rescript/Distributions/SampleSetDist/SampleSetDist.res
  packages/squiggle-lang/src/rescript/Distributions/SampleSetDist/SampleSetDist_Bandwidth.res
  packages/squiggle-lang/src/rescript/MagicNumbers.res
  packages/squiggle-lang/src/rescript/ReducerInterface/ReducerInterface_GenericDistribution.res
  packages/squiggle-lang/src/rescript/Utility/E.res
  packages/website/docs/Features/Functions.mdx
Labels: programming language

#443 `lang v0.2.8` and `components v0.2.16`
  packages/components/README.md
  packages/components/package.json
  packages/squiggle-lang/README.md
  packages/squiggle-lang/package.json
  packages/squiggle-lang/src/rescript/Distributions/DistributionOperation/DistributionOperation.res
  yarn.lock
Labels: operations
